config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :events, only: [:new, :create, :destroy, :index, :show]

  get    '/log_in',  to: 'sessions#new'
  post   '/log_in',  to: 'sessions#create'
  delete '/log_out', to: 'sessions#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord

  scope :future, -> { where("date >= :current_date",
                            current_date: DateTime.now) }
  scope :past, -> { where("date < :current_date",
                            current_date: DateTime.now) }


  belongs_to :creator, class_name: "User",
                       foreign_key: "user_id"
  has_and_belongs_to_many :attendees, 
                          class_name: "User",
                          foreign_key: "user_id",
                          association_foreign_key: 'event_id'

end

app/models/user.rb
class User < ApplicationRecord

  has_many  :events, dependent: :destroy
  has_and_belongs_to_many  :attended_events,
                           class_name:  "Event",
                           foreign_key: "event_id",
                           association_foreign_key: 'user_id'

  has_secure_password
  attr_accessor :remember_token

  before_save :downcase_email

  validates :name, presence: true,
                   length: {maximum: 30, minimum: 2},
                   uniqueness:{ case_sensitive: false }


  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 50 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness:{ case_sensitive: false }

  def upcoming_events
    self.attended_events.where("date >= :current_date",
                              current_date: DateTime.now)
  end

  def past_events
    self.attended_events.where("date < :current_date",
                              current_date: DateTime.now)
  end


  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  def self.new_token
    SecureRandom.urlsafe_base64
  end

  def self.digest(string)
    cost = ActivateModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                    BCrypt::Engine.cost
    BCrypt::Password.create(String, cost: cost)
  end

  private

  def downcase_email
    email.downcase!
  end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper


  private

    def logged_in_user
      unless logged_in?
        flash[:danger] = "Please log in."
        redirect_to log_in_path
      end
    end


end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_action :logged_in_user, only: [:new, :create, :destroy, :index, :show]

  def new
  end

  def index
    @upcoming_events = Event.future
    @past_events = Event.past
  end

  def show
    @event = Event.find(params[:id])
    @eventAttendees = @event.attendees
  end

  def create
    @event = current_user.events.build(event_params)
    if (@event.save)
      flash[:success] = "Event created!"
      redirect_to current_user
    else
      flash[:danger] = "Invalid event paramters."
      render 'new'
    end
  end

  def destroy
  end

  def event_params
    params.require(:event).permit(:name, :description, :date, :location)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by(name: params[:session][:name])
    if @user && @user.authenticate(params[:session][:password])
      log_in @user
      redirect_to @user
    else
      flash.now[:danger] = 'Invalid email/password combination.'
      render 'new'
    end
  end

  def destroy
    log_out(User.find_by(id: session[:user_id]))
    redirect_to log_in_path
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Your account has been created!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @upcoming_events = @user.upcoming_events
    @past_events = @user.past_events
  end

private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                :password_confirmation)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out(user)
    user.forget
    session.delete(:user_id)
  end

  def logged_in?
    !current_user.nil?
  end

  def current_user
    User.find_by(id: session[:user_id])
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_event.html.erb
<p>
  <b><%= event.name %></b> <br>
  <%= event.location %> <br>
  <%= event.date %> <br>
  Hosted by: <%= event.creator.name %> <br>
  <br>
</p>

app/views/events/index.html.erb
<h1>All Events</h1>
<h2>Upcoming Events</h2>
<%= render @upcoming_events %>
<h2>Past Events</h2>
<%= render @past_events %>

app/views/events/new.html.erb
<h1>Create an Event</h1>

<%= form_for(:event, url: events_path) do |f|  %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :description  %>
  <%= f.text_area :description %>

  <%= f.label :date %>
  <%= f.date_field :date %>

  <%= f.label :location %>
  <%= f.text_field :location %>

  <%= f.submit "Create Event" %>
<% end %>

app/views/events/show.html.erb
<h1> Event: <%= @event.name %></h1>
<%= render @event %>
<h2>People Attending:</h2>
<%= render @event.attendees %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= link_to "New Account", new_user_path %>
      <%= link_to "All Events", events_path %>

      <% if @current_user =current_user %>
        <p>Currently logged in as <%= @current_user.name %></p>
        <%= link_to "Log Out", log_out_path, method: :delete %>
        <%= link_to "My Profile", @current_user %>
      <% else %>
        <p>Currently not logged in.</p>
        <%= link_to "Log In", log_in_path %>
      <% end %>

      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
    <%= yield %>
    <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/users/_user.html.erb
<p> <%= user.name %></p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for(@user) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.text_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit 'Sign Up!' %>
<% end %>
  
  

app/views/users/show.html.erb
<h1> <%= @user.name %>'s Profile</h1>

<h3> <%= @user.name %>'s Events</h3>
<ul>
  <%= render @user.events %>
</ul>

<h3> <%= @user.name %>'s Upcoming Events:</h3>
<ul>
  <%= render @upcoming_events %>
</ul>
<h3> Past Events:</h3>
<ul>
  <%= render @past_events %>
</ul>